server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans
    username: root
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  application:
    name: trans-service #应用名称，会在 Eureka 中显示